<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>RentHaven</title>
</head>
<body>
<h1>RentHaven</h1>
<hr>
<h4>Реєстрація</h4>
<form action="/registration" method="post">
    Ім'я користувача: <input type="text" name="name"><br><br>
    Ел. почта: <input type="email" name="email"><br><br>
    Номер телефону: <input type="text" name="phoneNumber"><br><br>
    Пароль: <input type="password" name="password"><br><br>
    <input type="hidden" name="_csrf" value="${_csrf.token}">
    <input type="submit" value="Зареєструватися!"/>
</form>
<#if errorMessage??>
    <h2 style="color: #ff0000">${errorMessage}</h2>
</#if>
</body>
</html>
